name: Setup & Test

on:
  workflow_dispatch:
  push:
    branches:
      - "main"

permissions:
  contents: read
  packages: write

jobs:
  setup-env:
    name: Setup Environment
    runs-on: ubuntu-latest
    outputs:
      latest-tag: ${{ steps.latest-tag.outputs.latest-tag }}
    steps:
      - name: Get latest tag
        id: latest-tag
        run: echo "latest-tag=${{ github.ref == 'refs/heads/main' && 'dev-latest' || github.ref_name }}" >> "$GITHUB_OUTPUT"
  test:
    name: Test
    uses: ./.github/workflows/test.yml

  publish-test-results:
    name: Publish test results
    needs: test
    uses: ./.github/workflows/publish-test-results.yml

  publish-github-packages:
    name: Publish to GitHub Packages
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - uses: gradle/actions/setup-gradle@v4

      - name: Publish to GitHub Packages
        run: ./gradlew publishMavenJavaPublicationToGitHubPackagesRepository
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
